#!/usr/bin/env node
/**
 * build.js — plateaus/*.md → data.js 変換スクリプト
 *
 * 各プラトーの Markdown ファイル（YAML フロントマター付き）を読み込み、
 * app.js が使う data.js を自動生成する。
 *
 * 使い方:
 *   node build.js
 *
 * 外部ライブラリ不要（Node.js 標準モジュールのみ使用）。
 *
 * 思想的背景:
 *   Knuth の文芸的プログラミング — 「人間が読める形式」(Markdown) から
 *   「機械が読める形式」(JS) を生成する。Single Source of Truth は
 *   plateaus/ 内の Markdown ファイルである。
 */

const fs = require('fs');
const path = require('path');

const PLATEAUS_DIR = path.join(__dirname, 'plateaus');
const OUTPUT_FILE = path.join(__dirname, 'data.js');

// ---- YAML frontmatter parser (minimal, no dependencies) ----
function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) {
    throw new Error('YAML frontmatter not found');
  }

  const yamlStr = match[1];
  const body = match[2].trim();
  const meta = {};

  for (const line of yamlStr.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const colonIdx = trimmed.indexOf(':');
    if (colonIdx === -1) continue;

    const key = trimmed.slice(0, colonIdx).trim();
    let value = trimmed.slice(colonIdx + 1).trim();

    // Parse value types
    if (value.startsWith('[') && value.endsWith(']')) {
      // Array: [14, 35] or []
      const inner = value.slice(1, -1).trim();
      value = inner ? inner.split(',').map(v => {
        const n = Number(v.trim());
        return isNaN(n) ? v.trim() : n;
      }) : [];
    } else if (value.startsWith('"') && value.endsWith('"')) {
      // Quoted string
      value = value.slice(1, -1).replace(/\\"/g, '"');
    } else if (!isNaN(Number(value)) && value !== '') {
      // Number
      value = Number(value);
    }

    meta[key] = value;
  }

  return { meta, body };
}

// ---- Escape string for JS string literal ----
function escapeJsString(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, '\\n')
    .replace(/\r/g, '');
}

// ---- Main ----
function main() {
  // Read all .md files from plateaus/
  if (!fs.existsSync(PLATEAUS_DIR)) {
    console.error(`Error: ${PLATEAUS_DIR} does not exist.`);
    console.error('Create plateaus/ directory with Markdown files first.');
    process.exit(1);
  }

  const files = fs.readdirSync(PLATEAUS_DIR)
    .filter(f => f.endsWith('.md'))
    .sort();

  if (files.length === 0) {
    console.error('Error: No .md files found in plateaus/');
    process.exit(1);
  }

  console.log(`Found ${files.length} plateau files.`);

  // Parse all plateaus
  const plateaus = [];
  for (const file of files) {
    const filepath = path.join(PLATEAUS_DIR, file);
    const content = fs.readFileSync(filepath, 'utf-8');

    try {
      const { meta, body } = parseFrontmatter(content);

      // Validate required fields
      const required = ['id', 'title', 'cluster', 'clusterName', 'linksTo'];
      for (const field of required) {
        if (meta[field] === undefined) {
          throw new Error(`Missing required field: ${field}`);
        }
      }

      plateaus.push({
        id: meta.id,
        title: meta.title,
        cluster: meta.cluster,
        clusterName: meta.clusterName,
        linksTo: meta.linksTo,
        body: body
      });

      console.log(`  ✓ ${file} → §${meta.id} ${meta.title.slice(0, 30)}…`);
    } catch (err) {
      console.error(`  ✗ ${file}: ${err.message}`);
      process.exit(1);
    }
  }

  // Sort by id
  plateaus.sort((a, b) => a.id - b.id);

  // Generate data.js
  const entries = plateaus.map(p => {
    const linksToStr = `[${p.linksTo.join(', ')}]`;
    return `  {
    id: ${p.id},
    title: "${escapeJsString(p.title)}",
    cluster: ${p.cluster},
    clusterName: "${escapeJsString(p.clusterName)}",
    linksTo: ${linksToStr},
    body: "${escapeJsString(p.body)}"
  }`;
  });

  const output = `// Auto-generated by build.js — DO NOT EDIT DIRECTLY
// Edit the Markdown files in plateaus/ instead, then run: node build.js
const PLATEAUS = [
${entries.join(',\n')}
];

// Auto-generate backlinks
PLATEAUS.forEach(p => { p.linkedFrom = []; });
PLATEAUS.forEach(p => {
  p.linksTo.forEach(targetId => {
    const target = PLATEAUS.find(t => t.id === targetId);
    if (target && !target.linkedFrom.includes(p.id)) {
      target.linkedFrom.push(p.id);
    }
  });
});
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`\n✓ Generated ${OUTPUT_FILE}`);
  console.log(`  ${plateaus.length} plateaus, ${fs.statSync(OUTPUT_FILE).size} bytes`);
}

main();
